# Deploy minified application, installation manifests, and shields versions
name: Deploy Software System

on:
  workflow_dispatch:
  push:
    branches:
      # - main
      # - devel
      - deploy-test

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0
      - name: Setup Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: '3.10' 
      # Setup
      - name: Create Deployment Directories
        if: success() || failure()
        shell: bash
        run: mkdir -p deploy/{builds,manifests}/{main,devel,deploy-test}
      # Generate manifest + shields files for main branch
      - name: Checkout Main Branch
        id: checkout-main
        uses: actions/checkout@v7.0.0
        with:
          ref: 'main'
          path: branch-main
          clean: false
      - name: Legacy Temp Directory
        if: success() || failure()
        working-directory: branch-main
        shell: bash
        run: mkdir -p deploy/
      - name: "[MAIN] (LEGACY) Generate Installation Manifest and Shields JSON"
        id: manifest-main
        if: ${{ (success() || failure()) && steps.checkout-main.outcome == 'success' }}
        working-directory: branch-main
        run: python build/imgen.py shields
      - name: "[MAIN] Save Installation Manifest"
        if: ${{ (success() || failure()) && steps.manifest-main.outcome == 'success' }}
        working-directory: branch-main
        run: mv install_manifest.json ../deploy/manifests/main
      - name: "[MAIN] (LEGACY) Save Shields"
        if: ${{ (success() || failure()) && steps.manifest-main.outcome == 'success' }}
        working-directory: branch-main
        run: mv deploy/*.json ../deploy/
      # Generate manifest for devel branch
      - name: Checkout Development
        id: checkout-devel
        if: success() || failure()
        uses: actions/checkout@v7.0.0
        with:
          ref: 'devel'
          path: branch-devel
          clean: false
      - name: "[DEVEL] (LEGACY) Generate Installation Manifest"
        id: manifest-devel
        if: ${{ (success() || failure()) && steps.checkout-devel.outcome == 'success' }}
        working-directory: branch-devel
        run: python build/imgen.py
      - name: "[DEVEL] Save Installation Manifest"
        if: ${{ (success() || failure()) && steps.manifest-devel.outcome == 'success' }}
        working-directory: branch-devel
        run: mv install_manifest.json ../deploy/manifests/devel
      # Generate manifest and build for deploy-test branch
      - name: Checkout Deployment Test
        id: checkout-test
        if: success() || failure()
        uses: actions/checkout@v7.0.0
        with:
          ref: 'deploy-test'
          path: branch-test
          clean: false
      - name: "[DEPLOY-TEST] Generate Minified Code"
        id: minify-test
        if: ${{ (success() || failure()) && steps.checkout-test.outcome == 'success' }}
        working-directory: branch-test
        run: python build/gen_minified.py ../deploy/builds/deploy-test --deployment
      - name: "[DEPLOY-TEST] Generate Installation Manifest"
        id: manifest-test
        if: ${{ (success() || failure()) && steps.checkout-test.outcome == 'success' }}
        working-directory: branch-test
        run: python build/gen_manifest.py ../deploy/builds/deploy-test
      - name: "[DEPLOY-TEST] Save Installation Manifest"
        if: ${{ (success() || failure()) && steps.checkout-test.outcome == 'success' }}
        run: mv deploy/builds/deploy-test/installation_manifest.json deploy/manifests/deploy-test
      # All artifacts ready now, upload deploy directory
      - name: Upload Artifacts
        id: upload-artifacts
        if: ${{ (success() || failure()) && (steps.manifest-main.outcome == 'success' || steps.manifest-devel.outcome == 'success') }}
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          # Upload manifest JSON
          path: 'deploy/'
      - name: Deploy to GitHub Pages
        if: ${{ (success() || failure()) && steps.upload-artifacts.outcome == 'success' }}
        id: deployment
        uses: actions/deploy-pages@v3.0.2-node.24
